import { TrackType } from "./sharedtypes/sharedTypes";

export const data: TrackType[] = [
  {
    _id: 8,
    name: "Chase",
    author: "Alexander Nakarada",
    release_date: "2005-06-11",
    genre: ["Классическая музыка"],
    album: "Chase",
    logo: null,
    track_file: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    stared_user: [],
    duration_in_seconds: 205,
  },
  {
    _id: 9,
    name: "Summer",
    author: "Benjamin Tissot",
    release_date: "2017-08-15",
    genre: ["Электронная", "Лёгкая музыка"],
    album: "Royalty Free Music",
    logo: "https://example.com/logos/summer.jpg",
    track_file:
      "https://skypro-music-api.skyeng.tech/media/music_files/Benjamin_Tissot_-_Summer.mp3",
    stared_user: [12, 45],
    duration_in_seconds: 178,
  },
  {
    _id: 10,
    name: "Epic Adventure",
    author: "Scott Buckley",
    release_date: "2020-03-22",
    genre: ["Саундтрек", "Эпическая музыка"],
    album: "Legends",
    logo: "https://example.com/logos/epic.jpg",
    track_file:
      "https://skypro-music-api.skyeng.tech/media/music_files/Scott_Buckley_-_Epic_Adventure.mp3",
    stared_user: [7, 33, 89],
    duration_in_seconds: 237,
  },
  {
    _id: 11,
    name: "Jazz in Paris",
    author: "Media Right Productions",
    release_date: "2015-11-30",
    genre: ["Джаз"],
    album: "Paris Nights",
    logo: null,
    track_file:
      "https://skypro-music-api.skyeng.tech/media/music_files/Media_Right_-_Jazz_in_Paris.mp3",
    stared_user: [5, 21],
    duration_in_seconds: 142,
  },
  {
    _id: 12,
    name: "Acoustic Breeze",
    author: "Benjamin Tissot",
    release_date: "2018-05-14",
    genre: ["Акустическая", "Фоновая музыка"],
    album: "Serenity",
    logo: "https://example.com/logos/acoustic.jpg",
    track_file:
      "https://skypro-music-api.skyeng.tech/media/music_files/Benjamin_Tissot_-_Acoustic_Breeze.mp3",
    stared_user: [],
    duration_in_seconds: 156,
  },
  {
    _id: 13,
    name: "Piano Moment",
    author: "Keys of Moon",
    release_date: "2019-02-28",
    genre: ["Фортепианная музыка"],
    album: "Moonlight Sonatas",
    logo: "https://example.com/logos/piano.jpg",
    track_file:
      "https://skypro-music-api.skyeng.tech/media/music_files/Keys_of_Moon_-_Piano_Moment.mp3",
    stared_user: [15, 22, 40],
    duration_in_seconds: 189,
  },
];
